In [6]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt 
import seaborn as sns

In [7]:
ucas_path = "/Users/anatoly/Desktop/Imperial - Data Analytics/Capstone Project/HE Capstone - Final Data Sources/UCAS"
hesa_path = "/Users/anatoly/Desktop/Imperial - Data Analytics/Capstone Project/HE Capstone - Final Data Sources/HESA"

In [8]:
subject_df = pd.read_csv(ucas_path + "/UCAS June deadline 2026 - Subject group HECoS CAH1.csv")
hesa_subject = pd.read_csv(hesa_path + "/cah3_subject_level_data.csv")

In [9]:
subject_df.head()

,Year,Subject group HECoS CAH1,Age group,Domicile,Gender,Applications
0,2019,Unassigned,17 and under,Northern Ireland,Woman,0
1,2020,Unassigned,17 and under,Northern Ireland,Woman,0
2,2021,Unassigned,17 and under,Northern Ireland,Woman,0
3,2022,Unassigned,17 and under,Northern Ireland,Woman,0
4,2023,Unassigned,17 and under,Northern Ireland,Woman,0

In [10]:
hesa_subject['academic_year'].value_counts().sort_index()

academic_year
2006/2007    1252
2007/2008    1247
2008/2009    1256
2009/2010    1271
2010/2011    1280
2011/2012    2562
2012/2013    2606
2013/2014    2612
2014/2015    2600
2015/2016    3966
2016/2017    3969
2017/2018    3978
2018/2019    2732
2019/2020    2822
2020/2021    1408
2021/2022    1415
Name: count, dtype: int64

In [11]:
subject_df['Year'].value_counts()

Year
2019    10143
2020    10143
2021    10143
2022    10143
2023    10143
2024    10143
2025    10143
2026    10143
Name: count, dtype: int64

In [12]:
hesa_subject.head()

,time_period,time_identifier,geographic_level,country_code,country_name,academic_year,YAG,qualification_level,sex,CAH2_code,...,activity_not_captured,no_sust_dest,sust_emp_only,sust_emp_with_or_without_fs,sust_emp_fs_or_both,fs_with_or_without_sust_emp,earnings_include,earnings_LQ,earnings_median,earnings_UQ
0,201920,Tax year,National,K02000001,United Kingdom,2008/2009,10 YAG,Level 7,Male,CAH19-01,...,16.1,4,72.4,78.6,79.8,7.5,100,18800,29300,41000
1,201718,Tax year,National,K02000001,United Kingdom,2011/2012,5 YAG,First-degree,Male,CAH04-01,...,7.5,5.2,69.6,83.8,87.3,17.7,1170,19000,24800,32500
2,201718,Tax year,National,K02000001,United Kingdom,2011/2012,5 YAG,First-degree,Male,CAH15-04,...,4.9,3.8,75.3,90.6,91.3,16,510,20800,27400,33600
3,202021,Tax year,National,K02000001,United Kingdom,2018/2019,1 YAG,Level 7,Male,CAH16-01,...,6.4,5.9,75.9,84.7,87.7,11.9,2605,21200,30300,47400
4,201819,Tax year,National,K02000001,United Kingdom,2014/2015,3 YAG,First-degree,Male,CAH26-01,...,4.1,4.3,75.9,88.5,91.6,15.8,1050,20100,25200,31800

In [13]:
hesa_subject[hesa_subject['YAG'].isin(['1 YAG', '3 YAG'])] ['academic_year'].value_counts()

academic_year
2019/2020    2822
2018/2019    2732
2017/2018    2652
2016/2017    2646
2015/2016    2644
2021/2022    1415
2020/2021    1408
2013/2014    1306
2014/2015    1300
Name: count, dtype: int64

In [14]:
subject_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81144 entries, 0 to 81143
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      81144 non-null  int64
 1   Subject group HECoS CAH1  81144 non-null  object
 2   Age group                 81144 non-null  object
 3   Domicile                  81144 non-null  object
 4   Gender                    81144 non-null  object
 5   Applications              81144 non-null  int64
dtypes: int64(2), object(4)
memory usage: 3.7+ MB

In [15]:
subject_df['Subject group HECoS CAH1'].value_counts()

Subject group HECoS CAH1
Unassigned                                                 3528
(CAH20) historical, philosophical and religious studies    3528
(CAH05) veterinary sciences                                3528
(CAH16) law                                                3528
(CAH06) agriculture, food and related studies              3528
(CAH22) education and teaching                             3528
(CAH09) mathematical sciences                              3528
(CAH04) psychology                                         3528
(CAH07) physical sciences                                  3528
(CAH26) geography, earth and environmental studies         3528
(CAH11) computing                                          3528
(CAH01) medicine and dentistry                             3528
(CAH25) design, and creative and performing arts           3528
(CAH13) architecture, building and planning                3528
(CAH03) biological and sport sciences                      3528
(CAH15) social sciences                                    3528
(CAH17) business and management                            3528
(CAH23) combined and general studies                       3528
(CAH24) media, journalism and communications               3528
(CAH19) language and area studies                          3528
(CAH02) subjects allied to medicine                        3528
(CAH10) engineering and technology                         3528
All                                                        3528
Name: count, dtype: int64

In [16]:
subject_df['Gender'].value_counts()

Gender
Woman                  11592
Man                    11592
Unknown                11592
Undisclosed            11592
I use another term     11592
I prefer not to say    11592
All                    11592
Name: count, dtype: int64

In [17]:
subject_df['Domicile'].value_counts()

Domicile
Northern Ireland     11592
England              11592
Scotland             11592
Wales                11592
Not EU               11592
EU (excluding UK)    11592
All                  11592
Name: count, dtype: int64

In [18]:
subject_df['Age group'].value_counts()

Age group
17 and under    9016
18              9016
19              9016
20              9016
21 - 24         9016
25 - 29         9016
30 - 34         9016
35 and over     9016
All             9016
Name: count, dtype: int64

In [19]:
# --DATA CLEANING: UCAS Subject Groups -- 

# Remove the aggregate and unassigned subjects 
ucas_subject_clean = subject_df[~subject_df['Subject group HECoS CAH1'].isin(['All', 'Unassigned'])]

# Filtered to only include UK domicile — remove EU, Not EU, and All
ucas_subject_clean = ucas_subject_clean[ucas_subject_clean['Domicile'].isin(['Northern Ireland', 'England', 'Scotland', 'Wales'])]

# Filtered to standard undergraduate age of either 18 or 19
ucas_subject_clean = ucas_subject_clean[ucas_subject_clean['Age group'].isin(['18', '19'])] 

# Removed aggregate gender row but ensuring we maintain unbiased approach with gender disclosures 
ucas_subject_clean = ucas_subject_clean[~ucas_subject_clean['Gender'].isin(['All'])] 

# Filtered to analyse the time window 2019 - 2024
ucas_subject_clean = ucas_subject_clean[ucas_subject_clean['Year'].isin([2019, 2020, 2021, 2022, 2023, 2024])]

In [20]:
ucas_subject_clean['Subject group HECoS CAH1'].value_counts()

Subject group HECoS CAH1
(CAH25) design, and creative and performing arts           288
(CAH20) historical, philosophical and religious studies    288
(CAH16) law                                                288
(CAH06) agriculture, food and related studies              288
(CAH22) education and teaching                             288
(CAH09) mathematical sciences                              288
(CAH04) psychology                                         288
(CAH07) physical sciences                                  288
(CAH26) geography, earth and environmental studies         288
(CAH11) computing                                          288
(CAH01) medicine and dentistry                             288
(CAH10) engineering and technology                         288
(CAH13) architecture, building and planning                288
(CAH03) biological and sport sciences                      288
(CAH15) social sciences                                    288
(CAH17) business and management                            288
(CAH23) combined and general studies                       288
(CAH24) media, journalism and communications               288
(CAH19) language and area studies                          288
(CAH02) subjects allied to medicine                        288
(CAH05) veterinary sciences                                288
Name: count, dtype: int64

In [21]:
ucas_subject_clean['Domicile'].value_counts()

Domicile
Northern Ireland    1512
England             1512
Scotland            1512
Wales               1512
Name: count, dtype: int64

In [22]:
ucas_subject_clean['Age group'].value_counts()

Age group
18    3024
19    3024
Name: count, dtype: int64

In [23]:
ucas_subject_clean['Year'].value_counts()

Year
2019    1008
2020    1008
2021    1008
2022    1008
2023    1008
2024    1008
Name: count, dtype: int64

In [24]:
ucas_subject_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6048 entries, 184 to 46989
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      6048 non-null   int64
 1   Subject group HECoS CAH1  6048 non-null   object
 2   Age group                 6048 non-null   object
 3   Domicile                  6048 non-null   object
 4   Gender                    6048 non-null   object
 5   Applications              6048 non-null   int64
dtypes: int64(2), object(4)
memory usage: 330.8+ KB

In [25]:
# --- LOADING MULTIPLE DATASETS INTO ONE CELL - REMAINING UCAS 6 out of 7 ---

# Polar4 Data
polar4_df = pd.read_csv(ucas_path + "/UCAS June deadline 2026 - POLAR4 quintile.csv")

# Application Rates by Polar4
app_rates_polar4_df = pd.read_csv(ucas_path + "/UCAS June deadline 2026 - Application rates by POLAR4 quintile.csv")

# UCAS Provider by Category
ucas_provider_cat_df = pd.read_csv(ucas_path + "/UCAS June deadline 2026 - UCAS provider category.csv")

# Ethnic Groups 
ethnic_group_df = pd.read_csv(ucas_path + "/UCAS June deadline 2026 - Ethnic group.csv")

# UK Regions
uk_region_df = pd.read_csv(ucas_path + "/UCAS June deadline 2026 - UK region.csv")

# Gender
# We initially used a separate Gender df but the values in that
# amounted to only 4000, so there was not way to link it back 
# to the subject group, which meant it added limited value
# We therefore dropped it but for reference, the location is below:
# gender_df = pd.read_csv(ucas_path + "/UCAS June deadline 2026 - Gender.csv")

# Application Rates by IMD
app_rates_imd_df = pd.read_csv(ucas_path + "/UCAS June deadline 2026 - Application rates by IMD2019_NIMDM2017_SIMD2012_2016_2020_WIMD2019.csv")

In [26]:
# --- Loop for interating through UCAS datasets --- 
ucas_files = {
    'Polar4': polar4_df,
    'App Rates by Polar4': app_rates_polar4_df,
    'UCAS Provider Categ': ucas_provider_cat_df,
    'Ethnicity': ethnic_group_df,
    'UK Regions': uk_region_df,
    'IMD App Rates':app_rates_imd_df   
}

for name, df in ucas_files.items():
    print(name, df.shape)

Polar4 (22050, 6)
App Rates by Polar4 (4200, 8)
UCAS Provider Categ (26460, 7)
Ethnicity (22050, 6)
UK Regions (44100, 6)
IMD App Rates (4200, 8)

In [27]:
polar4_df.head()

   Year POLAR4 Quintile     Age group          Domicile Gender  Applicants
0  2017         Unknown  17 and under  Northern Ireland  Woman           0
1  2018         Unknown  17 and under  Northern Ireland  Woman           0
2  2019         Unknown  17 and under  Northern Ireland  Woman           0
3  2020         Unknown  17 and under  Northern Ireland  Woman           0
4  2021         Unknown  17 and under  Northern Ireland  Woman           0

In [28]:
hesa_underlying = pd.read_csv(hesa_path + "/underlying_data.csv")

In [29]:
hesa_underlying.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281343 entries, 0 to 281342
Data columns (total 41 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   time_period                  281343 non-null  int64
 1   time_identifier              281343 non-null  object
 2   geographic_level             281343 non-null  object
 3   country_code                 281343 non-null  object
 4   country_name                 281343 non-null  object
 5   provider_nation              281343 non-null  object
 6   region_code_current          281343 non-null  object
 7   region_name_current          281343 non-null  object
 8   academic_year                281343 non-null  object
 9   YAG                          281343 non-null  object
 10  qualification_level          281343 non-null  object
 11  country_of_domicile_grouped  281343 non-null  object
 12  nation_of_domicile           281343 non-null  object
 13  sex                          281343 non-null  object
 14  subject_name                 281343 non-null  object
 15  ethnicity_major              281343 non-null  object
 16  ethnicity_minor              281343 non-null  object
 17  inst_type                    281343 non-null  object
 18  study_mode                   281343 non-null  object
 19  age_band                     281343 non-null  object
 20  POLAR4                       281343 non-null  object
 21  prior_attainment             281343 non-null  object
 22  FSM                          281343 non-null  object
 23  IDACI                        281343 non-null  object
 24  region_name_origin           281343 non-null  object
 25  residence                    281343 non-null  object
 26  grads                        281343 non-null  int64
 27  grads_uk                     281343 non-null  int64
 28  unmatched_percent            281343 non-null  object
 29  overseas_percent             281343 non-null  object
 30  matched                      281343 non-null  object
 31  activity_not_captured        281343 non-null  object
 32  no_sust_dest                 281343 non-null  object
 33  sust_emp_only                281343 non-null  object
 34  sust_emp_with_or_without_fs  281343 non-null  object
 35  sust_emp_fs_or_both          281343 non-null  object
 36  fs_with_or_without_sust_emp  281343 non-null  object
 37  earnings_include             281343 non-null  object
 38  earnings_LQ                  281343 non-null  object
 39  earnings_median              281343 non-null  object
 40  earnings_UQ                  281343 non-null  object
dtypes: int64(3), object(38)
memory usage: 88.0+ MB

In [30]:
hesa_underlying['POLAR4'].value_counts()

POLAR4
Total        280839
1                84
5                84
4                84
2                84
3                84
Not known        84
Name: count, dtype: int64

In [31]:
hesa_underlying[hesa_underlying['POLAR4'].isin(['1', '2', '3', '4', '5'])] ['subject_name'].value_counts()

subject_name
Total    420
Name: count, dtype: int64

In [32]:
full_ucas_df = pd.read_csv(ucas_path + "/UCAS end of cycle 2025 - Subject group (HECoS) POLAR4 acceptances.csv")

In [33]:
full_ucas_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60850 entries, 0 to 60849
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      60850 non-null  int64
 1   Subject group HECoS CAH1  60850 non-null  object
 2   Subject group HECoS CAH3  60850 non-null  object
 3   POLAR4 Quintile           60850 non-null  object
 4   Main scheme applicant     60850 non-null  object
 5   Main scheme application   60850 non-null  object
 6   Accepted applicants       60850 non-null  int64
dtypes: int64(2), object(5)
memory usage: 3.2+ MB

In [34]:
full_ucas_df['POLAR4 Quintile'].value_counts()

POLAR4 Quintile
All           10158
Quintile 5     9685
Quintile 4     9582
Quintile 3     9468
Quintile 2     9304
Quintile 1     9056
Unknown        3597
Name: count, dtype: int64

In [35]:
# --DATA CLEANING: Main UCAS Dataset -- 

# Remove the unknown and all lines from the full_ucas_df
full_ucas_clean = full_ucas_df[~full_ucas_df['POLAR4 Quintile'].isin(['All', 'Unknown'])]

# Remove the year 2025 from the df, as this is the current year
full_ucas_clean = full_ucas_clean[~full_ucas_clean['Year'].isin([2025])]

full_ucas_clean = full_ucas_clean[~full_ucas_clean['Subject group HECoS CAH1'].isin(['All'])]

full_ucas_clean = full_ucas_clean[~full_ucas_clean['Subject group HECoS CAH3'].isin(['All'])]

# Keep only the 'all values' in Main scheme applicant
full_ucas_clean = full_ucas_clean[full_ucas_clean['Main scheme applicant'].isin(['All'])]

# Keep only the 'all values' in Main scheme applicant
full_ucas_clean = full_ucas_clean[full_ucas_clean['Main scheme application'].isin(['All'])]


# Remove the 'All' from 'Main Scheme Applicant' to avoid duplication
# full_ucas_clean = full_ucas_clean[~full_ucas_clean['Main scheme applicant'].isin(['All'])]

# Remove the 'All' from 'Main Scheme Application' to avoid duplication
# full_ucas_clean = full_ucas_clean[~full_ucas_clean['Main scheme application'].isin(['All'])]

In [36]:
full_ucas_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60850 entries, 0 to 60849
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      60850 non-null  int64
 1   Subject group HECoS CAH1  60850 non-null  object
 2   Subject group HECoS CAH3  60850 non-null  object
 3   POLAR4 Quintile           60850 non-null  object
 4   Main scheme applicant     60850 non-null  object
 5   Main scheme application   60850 non-null  object
 6   Accepted applicants       60850 non-null  int64
dtypes: int64(2), object(5)
memory usage: 3.2+ MB

In [37]:
full_ucas_clean['Year'].value_counts()

Year
2021    805
2019    804
2020    803
2022    800
2024    800
2023    796
Name: count, dtype: int64

In [38]:
full_ucas_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4808 entries, 53026 to 58631
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      4808 non-null   int64
 1   Subject group HECoS CAH1  4808 non-null   object
 2   Subject group HECoS CAH3  4808 non-null   object
 3   POLAR4 Quintile           4808 non-null   object
 4   Main scheme applicant     4808 non-null   object
 5   Main scheme application   4808 non-null   object
 6   Accepted applicants       4808 non-null   int64
dtypes: int64(2), object(5)
memory usage: 300.5+ KB

In [39]:
hesa_subject.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36976 entries, 0 to 36975
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   time_period                  36976 non-null  int64
 1   time_identifier              36976 non-null  object
 2   geographic_level             36976 non-null  object
 3   country_code                 36976 non-null  object
 4   country_name                 36976 non-null  object
 5   academic_year                36976 non-null  object
 6   YAG                          36976 non-null  object
 7   qualification_level          36976 non-null  object
 8   sex                          36976 non-null  object
 9   CAH2_code                    36976 non-null  object
 10  CAH2_subject                 36976 non-null  object
 11  CAH3_code                    36976 non-null  object
 12  CAH3_subject                 36976 non-null  object
 13  grads                        36976 non-null  int64
 14  grads_uk                     36976 non-null  int64
 15  unmatched_percent            36976 non-null  object
 16  overseas_percent             36976 non-null  object
 17  matched                      36976 non-null  object
 18  activity_not_captured        36976 non-null  object
 19  no_sust_dest                 36976 non-null  object
 20  sust_emp_only                36976 non-null  object
 21  sust_emp_with_or_without_fs  36976 non-null  object
 22  sust_emp_fs_or_both          36976 non-null  object
 23  fs_with_or_without_sust_emp  36976 non-null  object
 24  earnings_include             36976 non-null  object
 25  earnings_LQ                  36976 non-null  object
 26  earnings_median              36976 non-null  object
 27  earnings_UQ                  36976 non-null  object
dtypes: int64(3), object(25)
memory usage: 7.9+ MB

In [40]:
hesa_subject['YAG'].value_counts()

YAG
1 YAG     9571
3 YAG     9354
5 YAG     9161
10 YAG    8890
Name: count, dtype: int64

In [41]:
hesa_subject['qualification_level'].value_counts()

qualification_level
First-degree    12940
Level 7         12819
Level 8         11217
Name: count, dtype: int64

In [42]:
hesa_subject['academic_year'].value_counts()

academic_year
2017/2018    3978
2016/2017    3969
2015/2016    3966
2019/2020    2822
2018/2019    2732
2013/2014    2612
2012/2013    2606
2014/2015    2600
2011/2012    2562
2021/2022    1415
2020/2021    1408
2010/2011    1280
2009/2010    1271
2008/2009    1256
2006/2007    1252
2007/2008    1247
Name: count, dtype: int64

In [43]:
# --DATA CLEANING: Main HESA Dataset -- 

# Keep only the 1 and 3 YAG
hesa_subject_clean = hesa_subject[hesa_subject['YAG'].isin(['1 YAG', '3 YAG'])]

# Keep only the first degree information
hesa_subject_clean = hesa_subject_clean[hesa_subject_clean['qualification_level'].isin(['First-degree'])]

# Align the academic years with those in our UCAS dataset
hesa_subject_clean = hesa_subject_clean[hesa_subject_clean['academic_year'].isin(['2019/2020', '2020/2021', '2021/2022'])]

# Remove the 'Total' value from 'sex' column
hesa_subject_clean = hesa_subject_clean[~hesa_subject_clean['sex'].isin(['Total'])]

# Drop colums that re not required
hesa_subject_clean = hesa_subject_clean.drop(columns = ['time_identifier', 'geographic_level', 'country_code', 'country_name', 'CAH2_code', 'CAH2_subject'])

In [44]:
hesa_subject_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1304 entries, 66 to 24371
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   time_period                  1304 non-null   int64
 1   academic_year                1304 non-null   object
 2   YAG                          1304 non-null   object
 3   qualification_level          1304 non-null   object
 4   sex                          1304 non-null   object
 5   CAH3_code                    1304 non-null   object
 6   CAH3_subject                 1304 non-null   object
 7   grads                        1304 non-null   int64
 8   grads_uk                     1304 non-null   int64
 9   unmatched_percent            1304 non-null   object
 10  overseas_percent             1304 non-null   object
 11  matched                      1304 non-null   object
 12  activity_not_captured        1304 non-null   object
 13  no_sust_dest                 1304 non-null   object
 14  sust_emp_only                1304 non-null   object
 15  sust_emp_with_or_without_fs  1304 non-null   object
 16  sust_emp_fs_or_both          1304 non-null   object
 17  fs_with_or_without_sust_emp  1304 non-null   object
 18  earnings_include             1304 non-null   object
 19  earnings_LQ                  1304 non-null   object
 20  earnings_median              1304 non-null   object
 21  earnings_UQ                  1304 non-null   object
dtypes: int64(3), object(19)
memory usage: 234.3+ KB

In [45]:
hesa_subject_clean.value_counts(['sex'])

sex
Female    655
Male      649
Name: count, dtype: int64

In [46]:
len(full_ucas_clean)

4808

hesa_subject_clean.info()

In [47]:
hesa_subject_clean.value_counts(['time_period'])

time_period
202324         651
202122         327
202223         326
Name: count, dtype: int64

In [48]:
hesa_subject_clean.head()

,time_period,academic_year,YAG,qualification_level,sex,CAH3_code,CAH3_subject,grads,grads_uk,unmatched_percent,...,activity_not_captured,no_sust_dest,sust_emp_only,sust_emp_with_or_without_fs,sust_emp_fs_or_both,fs_with_or_without_sust_emp,earnings_include,earnings_LQ,earnings_median,earnings_UQ
66,202324,2019/2020,3 YAG,First-degree,Male,CAH02-06-01,Health sciences (non-specific),735,725,0.4,...,3.4,2,65.6,92.4,94.6,29,465,33300,42500,49000
202,202122,2019/2020,1 YAG,First-degree,Female,CAH02-06-04,Environmental and public health,270,265,0.4,...,1.7,7.2,50,79.2,91.2,41.2,130,16100,21900,27000
268,202324,2021/2022,1 YAG,First-degree,Male,CAH02-05-01,Medical technology,280,280,0.7,...,2.5,3.2,85.6,94.2,94.2,8.7,235,31100,35100,41400
407,202324,2021/2022,1 YAG,First-degree,Female,CAH02-04-04,Midwifery,1910,1895,0.4,...,1.4,2.5,87.8,95.6,96.1,8.3,1655,31500,36600,42100
411,202324,2021/2022,1 YAG,First-degree,Female,CAH03-01-06,Zoology,725,695,0.8,...,1.3,9.4,61.7,81.1,89.3,27.6,410,15400,21200,24900

In [49]:
hesa_subject_clean.to_csv('hesa_subject_clean.csv', index= False)

In [50]:
full_ucas_clean.to_csv('full_ucas_clean.csv', index = False)

In [51]:
subject_df['Applications'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 81144 entries, 0 to 81143
Series name: Applications
Non-Null Count  Dtype
--------------  -----
81144 non-null  int64
dtypes: int64(1)
memory usage: 634.1 KB

In [52]:
full_ucas_df['Main scheme applicant'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 60850 entries, 0 to 60849
Series name: Main scheme applicant
Non-Null Count  Dtype
--------------  -----
60850 non-null  object
dtypes: object(1)
memory usage: 475.5+ KB

In [53]:
full_ucas_df.head()

,Year,Subject group HECoS CAH1,Subject group HECoS CAH3,POLAR4 Quintile,Main scheme applicant,Main scheme application,Accepted applicants
0,2019,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,10
1,2020,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,15
2,2021,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,265
3,2022,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,20
4,2023,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,95

In [54]:
full_ucas_clean[(full_ucas_clean['Subject group HECoS CAH3'] == '(CAH16-01-01) law') & 
             (full_ucas_clean['Year'] == 2019) & 
             (full_ucas_clean['POLAR4 Quintile'] == 'Quintile 1')]

,Year,Subject group HECoS CAH1,Subject group HECoS CAH3,POLAR4 Quintile,Main scheme applicant,Main scheme application,Accepted applicants
54104,2019,(CAH16) law,(CAH16-01-01) law,Quintile 1,All,All,2945

In [55]:
full_ucas_clean[full_ucas_clean['Subject group HECoS CAH1'] == '(CAH16) law']

,Year,Subject group HECoS CAH1,Subject group HECoS CAH3,POLAR4 Quintile,Main scheme applicant,Main scheme application,Accepted applicants
54104,2019,(CAH16) law,(CAH16-01-01) law,Quintile 1,All,All,2945
54105,2020,(CAH16) law,(CAH16-01-01) law,Quintile 1,All,All,3255
54106,2021,(CAH16) law,(CAH16-01-01) law,Quintile 1,All,All,3365
54107,2022,(CAH16) law,(CAH16-01-01) law,Quintile 1,All,All,3445
54108,2023,(CAH16) law,(CAH16-01-01) law,Quintile 1,All,All,3370
54109,2024,(CAH16) law,(CAH16-01-01) law,Quintile 1,All,All,3755
55225,2019,(CAH16) law,(CAH16-01-01) law,Quintile 2,All,All,3580
55226,2020,(CAH16) law,(CAH16-01-01) law,Quintile 2,All,All,3805
55227,2021,(CAH16) law,(CAH16-01-01) law,Quintile 2,All,All,3940
55228,2022,(CAH16) law,(CAH16-01-01) law,Quintile 2,All,All,4030
55229,2023,(CAH16) law,(CAH16-01-01) law,Quintile 2,All,All,4145
55230,2024,(CAH16) law,(CAH16-01-01) law,Quintile 2,All,All,4275
56350,2019,(CAH16) law,(CAH16-01-01) law,Quintile 3,All,All,4190
56351,2020,(CAH16) law,(CAH16-01-01) law,Quintile 3,All,All,4390
56352,2021,(CAH16) law,(CAH16-01-01) law,Quintile 3,All,All,4520
56353,2022,(CAH16) law,(CAH16-01-01) law,Quintile 3,All,All,4450
56354,2023,(CAH16) law,(CAH16-01-01) law,Quintile 3,All,All,4540
56355,2024,(CAH16) law,(CAH16-01-01) law,Quintile 3,All,All,4875
57477,2019,(CAH16) law,(CAH16-01-01) law,Quintile 4,All,All,4950
57478,2020,(CAH16) law,(CAH16-01-01) law,Quintile 4,All,All,5065
57479,2021,(CAH16) law,(CAH16-01-01) law,Quintile 4,All,All,5125
57480,2022,(CAH16) law,(CAH16-01-01) law,Quintile 4,All,All,5095
57481,2023,(CAH16) law,(CAH16-01-01) law,Quintile 4,All,All,5270
57482,2024,(CAH16) law,(CAH16-01-01) law,Quintile 4,All,All,5535
58612,2019,(CAH16) law,(CAH16-01-01) law,Quintile 5,All,All,5605
58613,2020,(CAH16) law,(CAH16-01-01) law,Quintile 5,All,All,6020
58614,2021,(CAH16) law,(CAH16-01-01) law,Quintile 5,All,All,6170
58615,2022,(CAH16) law,(CAH16-01-01) law,Quintile 5,All,All,6005
58616,2023,(CAH16) law,(CAH16-01-01) law,Quintile 5,All,All,6220
58617,2024,(CAH16) law,(CAH16-01-01) law,Quintile 5,All,All,6445

In [56]:
full_ucas_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4808 entries, 53026 to 58631
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      4808 non-null   int64
 1   Subject group HECoS CAH1  4808 non-null   object
 2   Subject group HECoS CAH3  4808 non-null   object
 3   POLAR4 Quintile           4808 non-null   object
 4   Main scheme applicant     4808 non-null   object
 5   Main scheme application   4808 non-null   object
 6   Accepted applicants       4808 non-null   int64
dtypes: int64(2), object(5)
memory usage: 300.5+ KB

In [57]:
full_ucas_clean['Accepted applicants'].sum()

np.int64(2899340)

In [58]:
full_ucas_df.head()

,Year,Subject group HECoS CAH1,Subject group HECoS CAH3,POLAR4 Quintile,Main scheme applicant,Main scheme application,Accepted applicants
0,2019,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,10
1,2020,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,15
2,2021,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,265
3,2022,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,20
4,2023,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,Not main scheme applicant,Not main scheme application,95

In [59]:
full_ucas_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4808 entries, 53026 to 58631
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      4808 non-null   int64
 1   Subject group HECoS CAH1  4808 non-null   object
 2   Subject group HECoS CAH3  4808 non-null   object
 3   POLAR4 Quintile           4808 non-null   object
 4   Main scheme applicant     4808 non-null   object
 5   Main scheme application   4808 non-null   object
 6   Accepted applicants       4808 non-null   int64
dtypes: int64(2), object(5)
memory usage: 300.5+ KB

## Cleaning the IMD Dataset

In [60]:
imd_df = pd.read_csv('/Users/anatoly/Desktop/Imperial - Data Analytics/Capstone Project/HE Capstone - Final Data Sources/UCAS end of cycle 2025 - Subject group (HECoS) IMD2019 NIMDM2017 SIMD2012 2016 2020 WIMD2019 acceptances.csv')

In [61]:
imd_df.head()

,Year,Subject group HECoS CAH1,Subject group HECoS CAH3,IMD2019 NIMDM2017 SIMD2012 2016 2020 WIMD2019,Domicile,Main scheme applicant,Main scheme application,Accepted applicants
0,2019,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,England,Not main scheme applicant,Not main scheme application,10
1,2020,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,England,Not main scheme applicant,Not main scheme application,15
2,2021,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,England,Not main scheme applicant,Not main scheme application,265
3,2022,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,England,Not main scheme applicant,Not main scheme application,20
4,2023,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Unknown,England,Not main scheme applicant,Not main scheme application,95

In [62]:
imd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224449 entries, 0 to 224448
Data columns (total 8 columns):
 #   Column                                         Non-Null Count   Dtype
---  ------                                         --------------   -----
 0   Year                                           224449 non-null  int64
 1   Subject group HECoS CAH1                       224449 non-null  object
 2   Subject group HECoS CAH3                       224449 non-null  object
 3   IMD2019 NIMDM2017 SIMD2012 2016 2020 WIMD2019  224449 non-null  object
 4   Domicile                                       224449 non-null  object
 5   Main scheme applicant                          224449 non-null  object
 6   Main scheme application                        224449 non-null  object
 7   Accepted applicants                            224449 non-null  int64
dtypes: int64(2), object(6)
memory usage: 13.7+ MB

In [63]:
imd_df['Domicile'].value_counts()

Domicile
All                 61025
England             59144
Scotland            38929
Wales               36138
Northern Ireland    29213
Name: count, dtype: int64

In [64]:
imd_df['Year'].value_counts()

Year
2020    32765
2019    32518
2021    32066
2024    32012
2025    31866
2023    31614
2022    31608
Name: count, dtype: int64

In [65]:
# --DATA CLEANING: Main UCAS Dataset containing the WIMD/Deprivation Index Data-- 

# Remove the unknown and all lines from the imd_df
imd_df= imd_df[~imd_df['IMD2019 NIMDM2017 SIMD2012 2016 2020 WIMD2019'].isin(['All', 'Unknown'])]

# Remove the year 2025 from the df, as this is the current year
imd_df = imd_df[~imd_df['Year'].isin([2025])]

imd_df = imd_df[~imd_df['Subject group HECoS CAH1'].isin(['All'])]

imd_df = imd_df[~imd_df['Subject group HECoS CAH3'].isin(['All'])]

# Keep only the 'all values' in Main scheme applicant
imd_df = imd_df[imd_df['Main scheme applicant'].isin(['All'])]

# Keep only the 'all values' in Main scheme applicant
imd_df = imd_df[imd_df['Main scheme application'].isin(['All'])]

# Keep only 'All' values in domicile
imd_df = imd_df[imd_df['Domicile'].isin(['All'])]

In [66]:
len(imd_df)

4821

In [67]:
imd_df = imd_df.rename(columns = {'IMD2019 NIMDM2017 SIMD2012 2016 2020 WIMD2019':'IMD Aggregated'})

In [68]:
imd_df.head()

,Year,Subject group HECoS CAH1,Subject group HECoS CAH3,IMD Aggregated,Domicile,Main scheme applicant,Main scheme application,Accepted applicants
216608,2019,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Quintile 1,All,All,All,2600
216609,2020,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Quintile 1,All,All,All,2665
216610,2021,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Quintile 1,All,All,All,2605
216611,2022,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Quintile 1,All,All,All,2620
216612,2023,"(CAH25) design, and creative and performing arts",(CAH25-01-03) design studies,Quintile 1,All,All,All,2540

In [69]:
imd_df = imd_df.drop(columns = ['Domicile', 'Main scheme applicant', 'Main scheme application'])

In [70]:
imd_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4821 entries, 216608 to 222230
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Year                      4821 non-null   int64
 1   Subject group HECoS CAH1  4821 non-null   object
 2   Subject group HECoS CAH3  4821 non-null   object
 3   IMD Aggregated            4821 non-null   object
 4   Accepted applicants       4821 non-null   int64
dtypes: int64(2), object(3)
memory usage: 226.0+ KB

In [71]:
imd_df.to_csv('imd_clean.csv', index=False)

In [72]:
hesa_subject['academic_year'].value_counts().sort_index()

academic_year
2006/2007    1252
2007/2008    1247
2008/2009    1256
2009/2010    1271
2010/2011    1280
2011/2012    2562
2012/2013    2606
2013/2014    2612
2014/2015    2600
2015/2016    3966
2016/2017    3969
2017/2018    3978
2018/2019    2732
2019/2020    2822
2020/2021    1408
2021/2022    1415
Name: count, dtype: int64